def exception(e):
    print(f'EXCEPTION: {e}')